In [2]:
import numpy as np

In [3]:
#1. Create a 1D NumPy array containing numbers from 1 to 10
a = np.arange(1, 11)
print(a)


[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
# 2. Create a NumPy array using the list [5, 10, 15, 20, 25]
a2 = np.array([5, 10, 15, 20, 25])
print(a2)

[ 5 10 15 20 25]


In [5]:
#3.Create an array of 10 zeros

a3 = np.zeros(10)
print(a3)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
#4. Create an array of 8 ones.

a4 = np.ones(8)
print(a4)

[1. 1. 1. 1. 1. 1. 1. 1.]


In [7]:
# 5. Create an array using arange() from 0 to 20 with step 2.

a5 = np.arange(0, 20, 2)
print(a5)

[ 0  2  4  6  8 10 12 14 16 18]


In [9]:
# 6. Create an array using linspace() with 5 values between 10 and 50.
a6 = np.linspace(10, 50, 5)
print(a6)


[10. 20. 30. 40. 50.]


In [10]:
# 7. Create a 3 × 3 matrix filled with zeros.

a7 = np.zeros((3, 3))
print(a7)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
# 8. Create a 4 × 4 matrix filled with ones.
a8 = np.ones((4, 4))
print(a8)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [12]:
# 9. Create a 2 × 5 array containing numbers from 1 to 10 using reshape()
a9 = np.arange(1, 11).reshape(2, 5)
print(a9)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [13]:
# 10. Create a 3 × 4 array with numbers from 1 to 12.
a10 = np.arange(1, 13).reshape(3, 4)
print(a10)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [15]:
arr = np.array([10,20,30,40,50,60,70,80])
print(arr)

[10 20 30 40 50 60 70 80]


In [16]:
# 11. Print the first element of the array.
a11 = arr[0]
print(a11)


10


In [17]:
# 12. Print the last element of the array.
a12 = arr[-1]
print(a12)


80


In [18]:
 # 13. Print the 4th element of the array.
a13 = arr[3]
print(a13)

40


In [19]:
# 14. Print the element at index position 2.
a14 = arr[2]
print(a14)

30


In [20]:
# 15. Print the element at index position 5.
a15 = arr[5]
print(a15)

60


In [21]:
# 16. Print the element at index position 6.
a16 = arr[6]
print(a16)

70


In [22]:
# 17. Print the element at index position 3.
a17 = arr[3]
print(a17)

40


In [23]:
# 18. Create the given 2D NumPy array
a18 = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(a18)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
# 19. Create a 4 × 3 matrix with numbers from 1 to 12.

a19 = np.arange(1, 13).reshape(4, 3)
print(a19)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [25]:
# 20. Create a 5 × 2 matrix with numbers from 1 to 10.
a20 = np.arange(1, 11).reshape(5, 2)
print(a20)


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [26]:
arr2 = np.array([[10, 20, 30],
                  [40, 50, 60],
                  [70, 80, 90]])
print(arr2)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [27]:
# 21. Print the element 50.

a21 = arr2[1, 1]
print(a21)

50


In [28]:
# 22. Print the element 30.

a22 = arr2[0,2]
print(a22)

30


In [30]:
# 23. Print the element 70.
a23 = arr2[2,0]
print(a23)

70


In [31]:
# 24. Print the first row of the array.
a24 = arr2[0]
print(a24)

[10 20 30]


In [32]:
#25. Print the second column of the array.
a25 = arr2[:,1]
print(a25)

[20 50 80]
