## Advance indexing

In [1]:
import numpy as np

In [2]:
q1=np.arange(1,11)
print(q1)

[ 1  2  3  4  5  6  7  8  9 10]


In [6]:
a1=np.array([[12,13,14],[15,16,17]])
print(a1)

[[12 13 14]
 [15 16 17]]


In [7]:
a2 = ([10,20,30])
print(a2)

[10, 20, 30]


In [8]:
a1+a2

array([[22, 33, 44],
       [25, 36, 47]])

In [9]:
a3=q1.reshape(2,5)
a3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [11]:
a5 = np.array([[22],[27]])
a5

array([[22],
       [27]])

In [15]:
a=np.array([1,2,3])
b=np.array([4,5,6])
result=np.vstack((a,b))
print(result)

[[1 2 3]
 [4 5 6]]


In [16]:
a=np.array([1,2,3])
b=np.array([4,5,6])
result=np.hstack((a,b))
print(result)

[1 2 3 4 5 6]


In [17]:
a=np.array([1,2,3])
b=np.array([4,5,6])
result=np.row_stack((a,b))
print(result)

[[1 2 3]
 [4 5 6]]


/var/folders/_j/n88ll3ds1xjcsz0nc1yglgqw0000gn/T/ipykernel_1133/2751569255.py:3: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  result=np.row_stack((a,b))


In [18]:
a=np.array([1,2,3])
b=np.array([4,5,6])
result=np.column_stack((a,b))
print(result)

[[1 4]
 [2 5]
 [3 6]]


In [19]:
print(np.__version__)

2.1.3


In [25]:
num = int(input("Enter the number:"))
for i in range(1,11):
    value = num * i
    print(f"{num} * {i} = {value}")

Enter the number: 5


5 * 1 = 5
5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25
5 * 6 = 30
5 * 7 = 35
5 * 8 = 40
5 * 9 = 45
5 * 10 = 50
